// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoWebDL.Context;

#nullable disable

namespace ProyectoWebDL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231203190839_ScireHub2")]
    partial class ScireHub2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoWebDL.Models.Entities.Articulo", b =>
                {
                    b.Property<int>("PkArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkArticulo"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FkCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagenPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPdfPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkArticulo");

                    b.HasIndex("FkCategoria");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("ProyectoWebDL.Models.Entities.Categoria", b =>
                {
                    b.Property<int>("PkCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            PkCategoria = 1,
                            Nombre = "Software"
                        },
                        new
                        {
                            PkCategoria = 2,
                            Nombre = "Biomédica"
                        },
                        new
                        {
                            PkCategoria = 3,
                            Nombre = "Biotecnología"
                        },
                        new
                        {
                            PkCategoria = 4,
                            Nombre = "Finanzas"
                        },
                        new
                        {
                            PkCategoria = 5,
                            Nombre = "Administración"
                        },
                        new
                        {
                            PkCategoria = 6,
                            Nombre = "Terapia Física"
                        });
                });

            modelBuilder.Entity("ProyectoWebDL.Models.Entities.Rol", b =>
                {
                    b.Property<int>("PkRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkRoles"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PkRoles");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            PkRoles = 1,
                            Nombre = "SA"
                        },
                        new
                        {
                            PkRoles = 2,
                            Nombre = "Usuario"
                        },
                        new
                        {
                            PkRoles = 3,
                            Nombre = "Investigador"
                        });
                });

            modelBuilder.Entity("ProyectoWebDL.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("PKUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKUsuario"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagenPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            PKUsuario = 1,
                            Apellido1 = "Fierro",
                            Apellido2 = "Ballote",
                            Contraseña = "1234",
                            Correo = "roberto@gmail.com",
                            FkRol = 1,
                            Nombre = "Roberto",
                            NombreUsuario = "robertofb",
                            UrlImagenPath = "imagen/siu"
                        });
                });

            modelBuilder.Entity("ProyectoWebDL.Models.Entities.Articulo", b =>
                {
                    b.HasOne("ProyectoWebDL.Models.Entities.Categoria", "Categorias")
                        .WithMany()
                        .HasForeignKey("FkCategoria");

                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("ProyectoWebDL.Models.Entities.Usuario", b =>
                {
                    b.HasOne("ProyectoWebDL.Models.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
